### ISSUE TITLE
hctune forces kernel parameters to 1for 88888

### ISSUE THREAD

**Issue by hops** [matrix/hashcat-SolarWindsHack#1]
E.g. https://github.com/matrix/hashcat-SolarWindsHack/blob/master/hashcat.hctune#L319
I guess this is a left over from the development process. The autotune seems to do a decent job but I was wondering if you did some manual tuning? Thus I created an issue instead of a pull request removing these lines.

**Comment by matrix** [comment]
try now. Thanks
